name: Add new issues to Opsci GRMP Project

on:
  issues:
    types:
      - opened

permissions:
  issues: read
  contents: read
  repository-projects: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/vliz-be-opsci/projects/13
          github-token: ${{ secrets.GITHUB_TOKEN }}
